/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AbsenceRecord {
  'id' : bigint,
  'note' : [] | [string],
  'courseId' : bigint,
}
export interface Course {
  'id' : bigint,
  'name' : string,
  'plannedHoursPerWeek' : bigint,
  'semesterId' : bigint,
}
export interface ScheduleItem {
  'id' : bigint,
  'startTime' : string,
  'endTime' : string,
  'dayOfWeek' : string,
  'courseId' : bigint,
}
export interface Semester { 'id' : bigint, 'name' : string }
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAbsence' : ActorMethod<[AbsenceRecord], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<[Course], bigint>,
  'createScheduleItem' : ActorMethod<[ScheduleItem], bigint>,
  'createSemester' : ActorMethod<[Semester], bigint>,
  'deleteAbsence' : ActorMethod<[bigint], boolean>,
  'deleteCourse' : ActorMethod<[bigint], boolean>,
  'deleteScheduleItem' : ActorMethod<[bigint], boolean>,
  'deleteSemester' : ActorMethod<[bigint], boolean>,
  'getAbsences' : ActorMethod<[], Array<AbsenceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getCoursesSorted' : ActorMethod<[], Array<Course>>,
  'getScheduleItems' : ActorMethod<[], Array<ScheduleItem>>,
  'getSemesters' : ActorMethod<[], Array<Semester>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAbsence' : ActorMethod<[bigint, AbsenceRecord], boolean>,
  'updateCourse' : ActorMethod<[bigint, Course], boolean>,
  'updateScheduleItem' : ActorMethod<[bigint, ScheduleItem], boolean>,
  'updateSemester' : ActorMethod<[bigint, Semester], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];