/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AbsenceRecord = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Opt(IDL.Text),
  'courseId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'plannedHoursPerWeek' : IDL.Nat,
  'semesterId' : IDL.Nat,
});
export const ScheduleItem = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'dayOfWeek' : IDL.Text,
  'courseId' : IDL.Nat,
});
export const Semester = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAbsence' : IDL.Func([AbsenceRecord], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func([Course], [IDL.Nat], []),
  'createScheduleItem' : IDL.Func([ScheduleItem], [IDL.Nat], []),
  'createSemester' : IDL.Func([Semester], [IDL.Nat], []),
  'deleteAbsence' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteScheduleItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSemester' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAbsences' : IDL.Func([], [IDL.Vec(AbsenceRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getCoursesSorted' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getScheduleItems' : IDL.Func([], [IDL.Vec(ScheduleItem)], ['query']),
  'getSemesters' : IDL.Func([], [IDL.Vec(Semester)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAbsence' : IDL.Func([IDL.Nat, AbsenceRecord], [IDL.Bool], []),
  'updateCourse' : IDL.Func([IDL.Nat, Course], [IDL.Bool], []),
  'updateScheduleItem' : IDL.Func([IDL.Nat, ScheduleItem], [IDL.Bool], []),
  'updateSemester' : IDL.Func([IDL.Nat, Semester], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AbsenceRecord = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Opt(IDL.Text),
    'courseId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'plannedHoursPerWeek' : IDL.Nat,
    'semesterId' : IDL.Nat,
  });
  const ScheduleItem = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'dayOfWeek' : IDL.Text,
    'courseId' : IDL.Nat,
  });
  const Semester = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAbsence' : IDL.Func([AbsenceRecord], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func([Course], [IDL.Nat], []),
    'createScheduleItem' : IDL.Func([ScheduleItem], [IDL.Nat], []),
    'createSemester' : IDL.Func([Semester], [IDL.Nat], []),
    'deleteAbsence' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteScheduleItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSemester' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAbsences' : IDL.Func([], [IDL.Vec(AbsenceRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getCoursesSorted' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getScheduleItems' : IDL.Func([], [IDL.Vec(ScheduleItem)], ['query']),
    'getSemesters' : IDL.Func([], [IDL.Vec(Semester)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAbsence' : IDL.Func([IDL.Nat, AbsenceRecord], [IDL.Bool], []),
    'updateCourse' : IDL.Func([IDL.Nat, Course], [IDL.Bool], []),
    'updateScheduleItem' : IDL.Func([IDL.Nat, ScheduleItem], [IDL.Bool], []),
    'updateSemester' : IDL.Func([IDL.Nat, Semester], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };